import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Suspense } from "react";
import Marquee from "@/components/Marquee";
import Footer from "@/components/Footer";
import Loading from "./category/[categoryId]/loading";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const hindSiliguri = Hind_Siliguri({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin", "bengali"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${hindSiliguri.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Suspense fallback={<div><Loading /></div>}>
          <Header />
        
          <Marquee />
        <main  >
          
          {children}
        </main>
        <ToastContainer />
        <Footer />
        </Suspense>
      </body>
    </html>
  );
}
